// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Memtion struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Memtion) Reset()         { *m = Memtion{} }
func (m *Memtion) String() string { return proto.CompactTextString(m) }
func (*Memtion) ProtoMessage()    {}
func (*Memtion) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Memtion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Memtion.Unmarshal(m, b)
}
func (m *Memtion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Memtion.Marshal(b, m, deterministic)
}
func (m *Memtion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Memtion.Merge(m, src)
}
func (m *Memtion) XXX_Size() int {
	return xxx_messageInfo_Memtion.Size(m)
}
func (m *Memtion) XXX_DiscardUnknown() {
	xxx_messageInfo_Memtion.DiscardUnknown(m)
}

var xxx_messageInfo_Memtion proto.InternalMessageInfo

func (m *Memtion) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Memtion) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageBody struct {
	MessageType int32      `protobuf:"varint,2,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Text        string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Memtions    []*Memtion `protobuf:"bytes,4,rep,name=memtions,proto3" json:"memtions,omitempty"`
	ToUserId    int64      `protobuf:"varint,5,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	// int64            fromUserId  = 6; //发送者
	FromGroupId          int64    `protobuf:"varint,7,opt,name=fromGroupId,proto3" json:"fromGroupId,omitempty"`
	ToGroupId            int64    `protobuf:"varint,8,opt,name=toGroupId,proto3" json:"toGroupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageBody) Reset()         { *m = MessageBody{} }
func (m *MessageBody) String() string { return proto.CompactTextString(m) }
func (*MessageBody) ProtoMessage()    {}
func (*MessageBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *MessageBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBody.Unmarshal(m, b)
}
func (m *MessageBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBody.Marshal(b, m, deterministic)
}
func (m *MessageBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBody.Merge(m, src)
}
func (m *MessageBody) XXX_Size() int {
	return xxx_messageInfo_MessageBody.Size(m)
}
func (m *MessageBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBody proto.InternalMessageInfo

func (m *MessageBody) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *MessageBody) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageBody) GetMemtions() []*Memtion {
	if m != nil {
		return m.Memtions
	}
	return nil
}

func (m *MessageBody) GetToUserId() int64 {
	if m != nil {
		return m.ToUserId
	}
	return 0
}

func (m *MessageBody) GetFromGroupId() int64 {
	if m != nil {
		return m.FromGroupId
	}
	return 0
}

func (m *MessageBody) GetToGroupId() int64 {
	if m != nil {
		return m.ToGroupId
	}
	return 0
}

type SendMessageReq struct {
	Header               *ReqHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *MessageBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendMessageReq) Reset()         { *m = SendMessageReq{} }
func (m *SendMessageReq) String() string { return proto.CompactTextString(m) }
func (*SendMessageReq) ProtoMessage()    {}
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *SendMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageReq.Unmarshal(m, b)
}
func (m *SendMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageReq.Marshal(b, m, deterministic)
}
func (m *SendMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageReq.Merge(m, src)
}
func (m *SendMessageReq) XXX_Size() int {
	return xxx_messageInfo_SendMessageReq.Size(m)
}
func (m *SendMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageReq proto.InternalMessageInfo

func (m *SendMessageReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SendMessageReq) GetBody() *MessageBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type SendMessageAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendMessageAck) Reset()         { *m = SendMessageAck{} }
func (m *SendMessageAck) String() string { return proto.CompactTextString(m) }
func (*SendMessageAck) ProtoMessage()    {}
func (*SendMessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *SendMessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageAck.Unmarshal(m, b)
}
func (m *SendMessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageAck.Marshal(b, m, deterministic)
}
func (m *SendMessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageAck.Merge(m, src)
}
func (m *SendMessageAck) XXX_Size() int {
	return xxx_messageInfo_SendMessageAck.Size(m)
}
func (m *SendMessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageAck proto.InternalMessageInfo

func (m *SendMessageAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type MessageNotify struct {
	Header               *NotifyHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *MessageBody  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	FromUserId           int64         `protobuf:"varint,3,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	Avatar               string        `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string        `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MessageNotify) Reset()         { *m = MessageNotify{} }
func (m *MessageNotify) String() string { return proto.CompactTextString(m) }
func (*MessageNotify) ProtoMessage()    {}
func (*MessageNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *MessageNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageNotify.Unmarshal(m, b)
}
func (m *MessageNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageNotify.Marshal(b, m, deterministic)
}
func (m *MessageNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageNotify.Merge(m, src)
}
func (m *MessageNotify) XXX_Size() int {
	return xxx_messageInfo_MessageNotify.Size(m)
}
func (m *MessageNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MessageNotify proto.InternalMessageInfo

func (m *MessageNotify) GetHeader() *NotifyHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MessageNotify) GetBody() *MessageBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *MessageNotify) GetFromUserId() int64 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *MessageNotify) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *MessageNotify) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type RealTimeReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId               int64      `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64      `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RealTimeReq) Reset()         { *m = RealTimeReq{} }
func (m *RealTimeReq) String() string { return proto.CompactTextString(m) }
func (*RealTimeReq) ProtoMessage()    {}
func (*RealTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *RealTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeReq.Unmarshal(m, b)
}
func (m *RealTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeReq.Marshal(b, m, deterministic)
}
func (m *RealTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeReq.Merge(m, src)
}
func (m *RealTimeReq) XXX_Size() int {
	return xxx_messageInfo_RealTimeReq.Size(m)
}
func (m *RealTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeReq proto.InternalMessageInfo

func (m *RealTimeReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RealTimeReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RealTimeReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type RealTimeAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TcpAddr              string     `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"`
	Token                string     `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RoomId               int32      `protobuf:"varint,4,opt,name=roomId,proto3" json:"roomId,omitempty"`
	WsAddr               string     `protobuf:"bytes,5,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`
	HttpAddr             string     `protobuf:"bytes,6,opt,name=httpAddr,proto3" json:"httpAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RealTimeAck) Reset()         { *m = RealTimeAck{} }
func (m *RealTimeAck) String() string { return proto.CompactTextString(m) }
func (*RealTimeAck) ProtoMessage()    {}
func (*RealTimeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *RealTimeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeAck.Unmarshal(m, b)
}
func (m *RealTimeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeAck.Marshal(b, m, deterministic)
}
func (m *RealTimeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeAck.Merge(m, src)
}
func (m *RealTimeAck) XXX_Size() int {
	return xxx_messageInfo_RealTimeAck.Size(m)
}
func (m *RealTimeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeAck.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeAck proto.InternalMessageInfo

func (m *RealTimeAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RealTimeAck) GetTcpAddr() string {
	if m != nil {
		return m.TcpAddr
	}
	return ""
}

func (m *RealTimeAck) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RealTimeAck) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RealTimeAck) GetWsAddr() string {
	if m != nil {
		return m.WsAddr
	}
	return ""
}

func (m *RealTimeAck) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

type SimpleUser struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatart              string   `protobuf:"bytes,2,opt,name=avatart,proto3" json:"avatart,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleUser) Reset()         { *m = SimpleUser{} }
func (m *SimpleUser) String() string { return proto.CompactTextString(m) }
func (*SimpleUser) ProtoMessage()    {}
func (*SimpleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *SimpleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleUser.Unmarshal(m, b)
}
func (m *SimpleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleUser.Marshal(b, m, deterministic)
}
func (m *SimpleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleUser.Merge(m, src)
}
func (m *SimpleUser) XXX_Size() int {
	return xxx_messageInfo_SimpleUser.Size(m)
}
func (m *SimpleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleUser.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleUser proto.InternalMessageInfo

func (m *SimpleUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *SimpleUser) GetAvatart() string {
	if m != nil {
		return m.Avatart
	}
	return ""
}

func (m *SimpleUser) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RealTimeInfo struct {
	Token                string        `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RoomId               int32         `protobuf:"varint,4,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64         `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64         `protobuf:"varint,6,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Users                []*SimpleUser `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	HttpAddr             string        `protobuf:"bytes,8,opt,name=httpAddr,proto3" json:"httpAddr,omitempty"`
	WsAddr               string        `protobuf:"bytes,1,opt,name=wsAddr,proto3" json:"wsAddr,omitempty"`
	TcpAddr              string        `protobuf:"bytes,2,opt,name=tcpAddr,proto3" json:"tcpAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RealTimeInfo) Reset()         { *m = RealTimeInfo{} }
func (m *RealTimeInfo) String() string { return proto.CompactTextString(m) }
func (*RealTimeInfo) ProtoMessage()    {}
func (*RealTimeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *RealTimeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeInfo.Unmarshal(m, b)
}
func (m *RealTimeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeInfo.Marshal(b, m, deterministic)
}
func (m *RealTimeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeInfo.Merge(m, src)
}
func (m *RealTimeInfo) XXX_Size() int {
	return xxx_messageInfo_RealTimeInfo.Size(m)
}
func (m *RealTimeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeInfo proto.InternalMessageInfo

func (m *RealTimeInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RealTimeInfo) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RealTimeInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RealTimeInfo) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RealTimeInfo) GetUsers() []*SimpleUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *RealTimeInfo) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

func (m *RealTimeInfo) GetWsAddr() string {
	if m != nil {
		return m.WsAddr
	}
	return ""
}

func (m *RealTimeInfo) GetTcpAddr() string {
	if m != nil {
		return m.TcpAddr
	}
	return ""
}

type CancelRealTimeReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CancelRealTimeReq) Reset()         { *m = CancelRealTimeReq{} }
func (m *CancelRealTimeReq) String() string { return proto.CompactTextString(m) }
func (*CancelRealTimeReq) ProtoMessage()    {}
func (*CancelRealTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *CancelRealTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRealTimeReq.Unmarshal(m, b)
}
func (m *CancelRealTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRealTimeReq.Marshal(b, m, deterministic)
}
func (m *CancelRealTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRealTimeReq.Merge(m, src)
}
func (m *CancelRealTimeReq) XXX_Size() int {
	return xxx_messageInfo_CancelRealTimeReq.Size(m)
}
func (m *CancelRealTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRealTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRealTimeReq proto.InternalMessageInfo

func (m *CancelRealTimeReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CancelRealTimeAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CancelRealTimeAck) Reset()         { *m = CancelRealTimeAck{} }
func (m *CancelRealTimeAck) String() string { return proto.CompactTextString(m) }
func (*CancelRealTimeAck) ProtoMessage()    {}
func (*CancelRealTimeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *CancelRealTimeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRealTimeAck.Unmarshal(m, b)
}
func (m *CancelRealTimeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRealTimeAck.Marshal(b, m, deterministic)
}
func (m *CancelRealTimeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRealTimeAck.Merge(m, src)
}
func (m *CancelRealTimeAck) XXX_Size() int {
	return xxx_messageInfo_CancelRealTimeAck.Size(m)
}
func (m *CancelRealTimeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRealTimeAck.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRealTimeAck proto.InternalMessageInfo

func (m *CancelRealTimeAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type RealTimeNotify struct {
	Header               *NotifyHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IsConnect            bool          `protobuf:"varint,4,opt,name=IsConnect,proto3" json:"IsConnect,omitempty"`
	RealTimeInfo         *RealTimeInfo `protobuf:"bytes,5,opt,name=realTimeInfo,proto3" json:"realTimeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RealTimeNotify) Reset()         { *m = RealTimeNotify{} }
func (m *RealTimeNotify) String() string { return proto.CompactTextString(m) }
func (*RealTimeNotify) ProtoMessage()    {}
func (*RealTimeNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{11}
}

func (m *RealTimeNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RealTimeNotify.Unmarshal(m, b)
}
func (m *RealTimeNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RealTimeNotify.Marshal(b, m, deterministic)
}
func (m *RealTimeNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RealTimeNotify.Merge(m, src)
}
func (m *RealTimeNotify) XXX_Size() int {
	return xxx_messageInfo_RealTimeNotify.Size(m)
}
func (m *RealTimeNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RealTimeNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RealTimeNotify proto.InternalMessageInfo

func (m *RealTimeNotify) GetHeader() *NotifyHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RealTimeNotify) GetIsConnect() bool {
	if m != nil {
		return m.IsConnect
	}
	return false
}

func (m *RealTimeNotify) GetRealTimeInfo() *RealTimeInfo {
	if m != nil {
		return m.RealTimeInfo
	}
	return nil
}

type PollReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PollReq) Reset()         { *m = PollReq{} }
func (m *PollReq) String() string { return proto.CompactTextString(m) }
func (*PollReq) ProtoMessage()    {}
func (*PollReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{12}
}

func (m *PollReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollReq.Unmarshal(m, b)
}
func (m *PollReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollReq.Marshal(b, m, deterministic)
}
func (m *PollReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollReq.Merge(m, src)
}
func (m *PollReq) XXX_Size() int {
	return xxx_messageInfo_PollReq.Size(m)
}
func (m *PollReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PollReq.DiscardUnknown(m)
}

var xxx_messageInfo_PollReq proto.InternalMessageInfo

func (m *PollReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

//根据轮询结果请求相应消息数据
type PollAck struct {
	Header               *AckHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Msgs                 []*PollAck_Message `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
	RealTime             *PollAck_RealTime  `protobuf:"bytes,3,opt,name=realTime,proto3" json:"realTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PollAck) Reset()         { *m = PollAck{} }
func (m *PollAck) String() string { return proto.CompactTextString(m) }
func (*PollAck) ProtoMessage()    {}
func (*PollAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13}
}

func (m *PollAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollAck.Unmarshal(m, b)
}
func (m *PollAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollAck.Marshal(b, m, deterministic)
}
func (m *PollAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollAck.Merge(m, src)
}
func (m *PollAck) XXX_Size() int {
	return xxx_messageInfo_PollAck.Size(m)
}
func (m *PollAck) XXX_DiscardUnknown() {
	xxx_messageInfo_PollAck.DiscardUnknown(m)
}

var xxx_messageInfo_PollAck proto.InternalMessageInfo

func (m *PollAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PollAck) GetMsgs() []*PollAck_Message {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func (m *PollAck) GetRealTime() *PollAck_RealTime {
	if m != nil {
		return m.RealTime
	}
	return nil
}

type PollAck_Message struct {
	Count                int32    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	MessageKind          int32    `protobuf:"varint,2,opt,name=messageKind,proto3" json:"messageKind,omitempty"`
	GroupId              string   `protobuf:"bytes,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PollAck_Message) Reset()         { *m = PollAck_Message{} }
func (m *PollAck_Message) String() string { return proto.CompactTextString(m) }
func (*PollAck_Message) ProtoMessage()    {}
func (*PollAck_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13, 0}
}

func (m *PollAck_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollAck_Message.Unmarshal(m, b)
}
func (m *PollAck_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollAck_Message.Marshal(b, m, deterministic)
}
func (m *PollAck_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollAck_Message.Merge(m, src)
}
func (m *PollAck_Message) XXX_Size() int {
	return xxx_messageInfo_PollAck_Message.Size(m)
}
func (m *PollAck_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_PollAck_Message.DiscardUnknown(m)
}

var xxx_messageInfo_PollAck_Message proto.InternalMessageInfo

func (m *PollAck_Message) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PollAck_Message) GetMessageKind() int32 {
	if m != nil {
		return m.MessageKind
	}
	return 0
}

func (m *PollAck_Message) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type PollAck_RealTime struct {
	IsConnect            bool          `protobuf:"varint,2,opt,name=IsConnect,proto3" json:"IsConnect,omitempty"`
	RealTimeInfo         *RealTimeInfo `protobuf:"bytes,3,opt,name=realTimeInfo,proto3" json:"realTimeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PollAck_RealTime) Reset()         { *m = PollAck_RealTime{} }
func (m *PollAck_RealTime) String() string { return proto.CompactTextString(m) }
func (*PollAck_RealTime) ProtoMessage()    {}
func (*PollAck_RealTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{13, 1}
}

func (m *PollAck_RealTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PollAck_RealTime.Unmarshal(m, b)
}
func (m *PollAck_RealTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PollAck_RealTime.Marshal(b, m, deterministic)
}
func (m *PollAck_RealTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PollAck_RealTime.Merge(m, src)
}
func (m *PollAck_RealTime) XXX_Size() int {
	return xxx_messageInfo_PollAck_RealTime.Size(m)
}
func (m *PollAck_RealTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PollAck_RealTime.DiscardUnknown(m)
}

var xxx_messageInfo_PollAck_RealTime proto.InternalMessageInfo

func (m *PollAck_RealTime) GetIsConnect() bool {
	if m != nil {
		return m.IsConnect
	}
	return false
}

func (m *PollAck_RealTime) GetRealTimeInfo() *RealTimeInfo {
	if m != nil {
		return m.RealTimeInfo
	}
	return nil
}

//获取消息列表
type GetMessageUserReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessageUserReq) Reset()         { *m = GetMessageUserReq{} }
func (m *GetMessageUserReq) String() string { return proto.CompactTextString(m) }
func (*GetMessageUserReq) ProtoMessage()    {}
func (*GetMessageUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{14}
}

func (m *GetMessageUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageUserReq.Unmarshal(m, b)
}
func (m *GetMessageUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageUserReq.Marshal(b, m, deterministic)
}
func (m *GetMessageUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageUserReq.Merge(m, src)
}
func (m *GetMessageUserReq) XXX_Size() int {
	return xxx_messageInfo_GetMessageUserReq.Size(m)
}
func (m *GetMessageUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageUserReq proto.InternalMessageInfo

func (m *GetMessageUserReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetMessageUserAck struct {
	Header               *AckHeader                       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Users                []*GetMessageUserAck_MessageUser `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetMessageUserAck) Reset()         { *m = GetMessageUserAck{} }
func (m *GetMessageUserAck) String() string { return proto.CompactTextString(m) }
func (*GetMessageUserAck) ProtoMessage()    {}
func (*GetMessageUserAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{15}
}

func (m *GetMessageUserAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageUserAck.Unmarshal(m, b)
}
func (m *GetMessageUserAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageUserAck.Marshal(b, m, deterministic)
}
func (m *GetMessageUserAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageUserAck.Merge(m, src)
}
func (m *GetMessageUserAck) XXX_Size() int {
	return xxx_messageInfo_GetMessageUserAck.Size(m)
}
func (m *GetMessageUserAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageUserAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageUserAck proto.InternalMessageInfo

func (m *GetMessageUserAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetMessageUserAck) GetUsers() []*GetMessageUserAck_MessageUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetMessageUserAck_MessageUser struct {
	UserId               int64             `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64             `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Nickname             string            `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string            `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Count                int32             `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	FromGroupId          int64             `protobuf:"varint,7,opt,name=fromGroupId,proto3" json:"fromGroupId,omitempty"`
	Messages             []*MessageAckBody `protobuf:"bytes,10,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMessageUserAck_MessageUser) Reset()         { *m = GetMessageUserAck_MessageUser{} }
func (m *GetMessageUserAck_MessageUser) String() string { return proto.CompactTextString(m) }
func (*GetMessageUserAck_MessageUser) ProtoMessage()    {}
func (*GetMessageUserAck_MessageUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{15, 0}
}

func (m *GetMessageUserAck_MessageUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageUserAck_MessageUser.Unmarshal(m, b)
}
func (m *GetMessageUserAck_MessageUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageUserAck_MessageUser.Marshal(b, m, deterministic)
}
func (m *GetMessageUserAck_MessageUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageUserAck_MessageUser.Merge(m, src)
}
func (m *GetMessageUserAck_MessageUser) XXX_Size() int {
	return xxx_messageInfo_GetMessageUserAck_MessageUser.Size(m)
}
func (m *GetMessageUserAck_MessageUser) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageUserAck_MessageUser.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageUserAck_MessageUser proto.InternalMessageInfo

func (m *GetMessageUserAck_MessageUser) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMessageUserAck_MessageUser) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetMessageUserAck_MessageUser) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetMessageUserAck_MessageUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GetMessageUserAck_MessageUser) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetMessageUserAck_MessageUser) GetFromGroupId() int64 {
	if m != nil {
		return m.FromGroupId
	}
	return 0
}

func (m *GetMessageUserAck_MessageUser) GetMessages() []*MessageAckBody {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetMessageReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId               int64      `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64      `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessageReq) Reset()         { *m = GetMessageReq{} }
func (m *GetMessageReq) String() string { return proto.CompactTextString(m) }
func (*GetMessageReq) ProtoMessage()    {}
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{16}
}

func (m *GetMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageReq.Unmarshal(m, b)
}
func (m *GetMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageReq.Marshal(b, m, deterministic)
}
func (m *GetMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageReq.Merge(m, src)
}
func (m *GetMessageReq) XXX_Size() int {
	return xxx_messageInfo_GetMessageReq.Size(m)
}
func (m *GetMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageReq proto.InternalMessageInfo

func (m *GetMessageReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetMessageReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetMessageReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type MessageAckBody struct {
	Text                 string     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	FromUid              int64      `protobuf:"varint,2,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	ToUid                int64      `protobuf:"varint,3,opt,name=toUid,proto3" json:"toUid,omitempty"`
	GroupId              int64      `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	MessageType          int32      `protobuf:"varint,5,opt,name=messageType,proto3" json:"messageType,omitempty"`
	MediaUrl             string     `protobuf:"bytes,6,opt,name=mediaUrl,proto3" json:"mediaUrl,omitempty"`
	CreateTime           int64      `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64      `protobuf:"varint,8,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Memtions             []*Memtion `protobuf:"bytes,16,rep,name=memtions,proto3" json:"memtions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageAckBody) Reset()         { *m = MessageAckBody{} }
func (m *MessageAckBody) String() string { return proto.CompactTextString(m) }
func (*MessageAckBody) ProtoMessage()    {}
func (*MessageAckBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{17}
}

func (m *MessageAckBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageAckBody.Unmarshal(m, b)
}
func (m *MessageAckBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageAckBody.Marshal(b, m, deterministic)
}
func (m *MessageAckBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageAckBody.Merge(m, src)
}
func (m *MessageAckBody) XXX_Size() int {
	return xxx_messageInfo_MessageAckBody.Size(m)
}
func (m *MessageAckBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageAckBody.DiscardUnknown(m)
}

var xxx_messageInfo_MessageAckBody proto.InternalMessageInfo

func (m *MessageAckBody) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageAckBody) GetFromUid() int64 {
	if m != nil {
		return m.FromUid
	}
	return 0
}

func (m *MessageAckBody) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *MessageAckBody) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *MessageAckBody) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *MessageAckBody) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *MessageAckBody) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageAckBody) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *MessageAckBody) GetMemtions() []*Memtion {
	if m != nil {
		return m.Memtions
	}
	return nil
}

type GetMessageAck struct {
	Header               *AckHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Messages             []*MessageAckBody `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMessageAck) Reset()         { *m = GetMessageAck{} }
func (m *GetMessageAck) String() string { return proto.CompactTextString(m) }
func (*GetMessageAck) ProtoMessage()    {}
func (*GetMessageAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{18}
}

func (m *GetMessageAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageAck.Unmarshal(m, b)
}
func (m *GetMessageAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageAck.Marshal(b, m, deterministic)
}
func (m *GetMessageAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageAck.Merge(m, src)
}
func (m *GetMessageAck) XXX_Size() int {
	return xxx_messageInfo_GetMessageAck.Size(m)
}
func (m *GetMessageAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageAck.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageAck proto.InternalMessageInfo

func (m *GetMessageAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetMessageAck) GetMessages() []*MessageAckBody {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SetReadReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId               int64      `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetReadReq) Reset()         { *m = SetReadReq{} }
func (m *SetReadReq) String() string { return proto.CompactTextString(m) }
func (*SetReadReq) ProtoMessage()    {}
func (*SetReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{19}
}

func (m *SetReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReadReq.Unmarshal(m, b)
}
func (m *SetReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReadReq.Marshal(b, m, deterministic)
}
func (m *SetReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReadReq.Merge(m, src)
}
func (m *SetReadReq) XXX_Size() int {
	return xxx_messageInfo_SetReadReq.Size(m)
}
func (m *SetReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReadReq proto.InternalMessageInfo

func (m *SetReadReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SetReadReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SetReadAck struct {
	Header               *AckHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetReadAck) Reset()         { *m = SetReadAck{} }
func (m *SetReadAck) String() string { return proto.CompactTextString(m) }
func (*SetReadAck) ProtoMessage()    {}
func (*SetReadAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{20}
}

func (m *SetReadAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReadAck.Unmarshal(m, b)
}
func (m *SetReadAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReadAck.Marshal(b, m, deterministic)
}
func (m *SetReadAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReadAck.Merge(m, src)
}
func (m *SetReadAck) XXX_Size() int {
	return xxx_messageInfo_SetReadAck.Size(m)
}
func (m *SetReadAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReadAck.DiscardUnknown(m)
}

var xxx_messageInfo_SetReadAck proto.InternalMessageInfo

func (m *SetReadAck) GetHeader() *AckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Memtion)(nil), "protocol.Memtion")
	proto.RegisterType((*MessageBody)(nil), "protocol.MessageBody")
	proto.RegisterType((*SendMessageReq)(nil), "protocol.SendMessageReq")
	proto.RegisterType((*SendMessageAck)(nil), "protocol.SendMessageAck")
	proto.RegisterType((*MessageNotify)(nil), "protocol.MessageNotify")
	proto.RegisterType((*RealTimeReq)(nil), "protocol.RealTimeReq")
	proto.RegisterType((*RealTimeAck)(nil), "protocol.RealTimeAck")
	proto.RegisterType((*SimpleUser)(nil), "protocol.SimpleUser")
	proto.RegisterType((*RealTimeInfo)(nil), "protocol.RealTimeInfo")
	proto.RegisterType((*CancelRealTimeReq)(nil), "protocol.CancelRealTimeReq")
	proto.RegisterType((*CancelRealTimeAck)(nil), "protocol.CancelRealTimeAck")
	proto.RegisterType((*RealTimeNotify)(nil), "protocol.RealTimeNotify")
	proto.RegisterType((*PollReq)(nil), "protocol.PollReq")
	proto.RegisterType((*PollAck)(nil), "protocol.PollAck")
	proto.RegisterType((*PollAck_Message)(nil), "protocol.PollAck.Message")
	proto.RegisterType((*PollAck_RealTime)(nil), "protocol.PollAck.RealTime")
	proto.RegisterType((*GetMessageUserReq)(nil), "protocol.GetMessageUserReq")
	proto.RegisterType((*GetMessageUserAck)(nil), "protocol.GetMessageUserAck")
	proto.RegisterType((*GetMessageUserAck_MessageUser)(nil), "protocol.GetMessageUserAck.MessageUser")
	proto.RegisterType((*GetMessageReq)(nil), "protocol.GetMessageReq")
	proto.RegisterType((*MessageAckBody)(nil), "protocol.MessageAckBody")
	proto.RegisterType((*GetMessageAck)(nil), "protocol.GetMessageAck")
	proto.RegisterType((*SetReadReq)(nil), "protocol.SetReadReq")
	proto.RegisterType((*SetReadAck)(nil), "protocol.SetReadAck")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0x96, 0x9d, 0x38, 0x71, 0x26, 0xbd, 0x8a, 0x2e, 0xe5, 0x64, 0xa2, 0x13, 0x8a, 0xfc, 0x42,
	0x01, 0x5d, 0x1e, 0x02, 0x9c, 0x04, 0xd2, 0x49, 0x17, 0xfa, 0x70, 0x44, 0xe8, 0x10, 0x6c, 0xaf,
	0x2f, 0xf0, 0xe4, 0xda, 0xdb, 0xc6, 0x8a, 0xed, 0x4d, 0xed, 0x0d, 0x90, 0xbf, 0x02, 0xff, 0x83,
	0x47, 0x7e, 0x02, 0xbf, 0x01, 0xc4, 0x0b, 0x3f, 0x03, 0xed, 0xac, 0xd7, 0xde, 0x4d, 0x28, 0xc5,
	0x15, 0xe2, 0xc9, 0x9e, 0xd9, 0xd9, 0xd9, 0xd9, 0xef, 0x9b, 0xd9, 0x19, 0x80, 0x78, 0x15, 0x89,
	0xd9, 0xa6, 0xe4, 0x82, 0x13, 0x1f, 0x3f, 0x31, 0xcf, 0x26, 0x47, 0x2b, 0x16, 0x25, 0xac, 0x54,
	0xfa, 0xf0, 0x63, 0x18, 0xbe, 0x62, 0xb9, 0x48, 0x79, 0x41, 0x1e, 0xc3, 0x60, 0x5b, 0xb1, 0x72,
	0x99, 0x04, 0xce, 0xd4, 0x39, 0xeb, 0xd1, 0x5a, 0x22, 0x04, 0xfa, 0x82, 0xfd, 0x20, 0x02, 0x77,
	0xea, 0x9c, 0x8d, 0x28, 0xfe, 0x87, 0xbf, 0x3a, 0x30, 0x7e, 0xc5, 0xaa, 0x2a, 0xba, 0x61, 0x9f,
	0xf1, 0x64, 0x47, 0xa6, 0x30, 0xce, 0x95, 0xf8, 0x7a, 0xb7, 0x61, 0x68, 0xea, 0x51, 0x53, 0xd5,
	0x78, 0xe9, 0xb5, 0x5e, 0xc8, 0x53, 0xf0, 0x73, 0x75, 0x78, 0x15, 0xf4, 0xa7, 0xbd, 0xb3, 0xf1,
	0xfc, 0x64, 0xa6, 0xe3, 0x9c, 0xd5, 0x61, 0xd1, 0xc6, 0x84, 0x4c, 0xc0, 0x17, 0xfc, 0x52, 0x85,
	0xe8, 0x61, 0x88, 0x8d, 0x2c, 0x03, 0xb8, 0x2e, 0x79, 0xfe, 0xb2, 0xe4, 0xdb, 0xcd, 0x32, 0x09,
	0x86, 0xb8, 0x6c, 0xaa, 0xc8, 0x13, 0x18, 0x09, 0xae, 0xd7, 0x7d, 0x5c, 0x6f, 0x15, 0xe1, 0x0a,
	0x8e, 0x2f, 0x58, 0x91, 0xd4, 0x77, 0xa2, 0xec, 0x96, 0x7c, 0x00, 0x03, 0x85, 0x14, 0xc2, 0x31,
	0x9e, 0xbf, 0xd9, 0x86, 0x46, 0xd9, 0xed, 0xe7, 0xb8, 0x44, 0x6b, 0x13, 0xf2, 0x1e, 0xf4, 0xaf,
	0x78, 0xb2, 0xc3, 0x8b, 0x8f, 0xe7, 0x6f, 0x99, 0xb7, 0x68, 0x40, 0xa2, 0x68, 0x12, 0x3e, 0xb7,
	0x4e, 0x5a, 0xc4, 0xeb, 0x7f, 0x3a, 0x69, 0x11, 0xaf, 0xed, 0x93, 0xc2, 0x5f, 0x1c, 0x78, 0x54,
	0xef, 0xfd, 0x92, 0x8b, 0xf4, 0x7a, 0x47, 0x66, 0x7b, 0xdb, 0x1f, 0xb7, 0xdb, 0x95, 0xc5, 0x83,
	0x63, 0x25, 0xef, 0x00, 0x48, 0x08, 0x6b, 0xcc, 0x7b, 0x08, 0x9a, 0xa1, 0x91, 0x29, 0x13, 0x7d,
	0x17, 0x89, 0xa8, 0x0c, 0xfa, 0x48, 0x6b, 0x2d, 0x49, 0xa6, 0x8a, 0x34, 0x5e, 0x17, 0x51, 0xce,
	0x90, 0xa9, 0x11, 0x6d, 0xe4, 0x30, 0x83, 0x31, 0x65, 0x51, 0xf6, 0x3a, 0xcd, 0xbb, 0xc3, 0xdc,
	0xa6, 0xa8, 0x6b, 0xa5, 0x68, 0x00, 0xc3, 0x9b, 0x9a, 0x59, 0x15, 0xa4, 0x16, 0xc3, 0x9f, 0x9d,
	0xf6, 0xb8, 0xae, 0x58, 0x4b, 0xb7, 0x22, 0xde, 0x2c, 0x92, 0xa4, 0xac, 0x93, 0x5f, 0x8b, 0xe4,
	0x14, 0x3c, 0xc1, 0xd7, 0xac, 0xa8, 0xd3, 0x59, 0x09, 0x32, 0xbc, 0x92, 0xf3, 0x7c, 0x99, 0x20,
	0x1c, 0x1e, 0xad, 0x25, 0xa9, 0xff, 0xbe, 0x42, 0x37, 0x0a, 0x8c, 0x5a, 0x92, 0x30, 0xad, 0x84,
	0x50, 0x07, 0x0c, 0x14, 0x4c, 0x5a, 0x0e, 0xbf, 0x01, 0xb8, 0x48, 0xf3, 0x4d, 0xc6, 0x24, 0xd4,
	0x16, 0xa0, 0x8e, 0x0d, 0xa8, 0x8c, 0x52, 0xc1, 0xae, 0x4b, 0x54, 0x8b, 0x06, 0x5c, 0x3d, 0x13,
	0xae, 0xf0, 0x4f, 0x07, 0x8e, 0x34, 0x28, 0xcb, 0xe2, 0x9a, 0x77, 0xbf, 0xce, 0xd6, 0xac, 0xc2,
	0xbf, 0x61, 0x61, 0x60, 0xb1, 0x40, 0xde, 0x07, 0x4f, 0xda, 0x54, 0xc1, 0x10, 0xab, 0xfc, 0xb4,
	0x05, 0xbd, 0xbd, 0x23, 0x55, 0x26, 0x16, 0x28, 0xbe, 0x0d, 0x8a, 0x01, 0xa4, 0x63, 0x01, 0x79,
	0x27, 0x51, 0xe1, 0x0b, 0x38, 0x39, 0x8f, 0x8a, 0x98, 0x65, 0x0f, 0xcd, 0xb9, 0x43, 0x0f, 0x9d,
	0x4b, 0xf6, 0x47, 0x07, 0x8e, 0xf5, 0xe6, 0x07, 0xd6, 0xec, 0x13, 0x18, 0x2d, 0xab, 0x73, 0x5e,
	0x14, 0x2c, 0x16, 0xc8, 0x86, 0x4f, 0x5b, 0x05, 0xf9, 0x14, 0x8e, 0x4a, 0x83, 0x4e, 0xa4, 0xc5,
	0xf2, 0x69, 0x92, 0x4d, 0x2d, 0xdb, 0xf0, 0x19, 0x0c, 0xbf, 0xe2, 0x59, 0xd6, 0x19, 0x96, 0xdf,
	0x5c, 0xb5, 0xb1, 0x73, 0x51, 0x3d, 0x85, 0x7e, 0x5e, 0xdd, 0x54, 0x81, 0x8b, 0xa9, 0xf0, 0x76,
	0x6b, 0x5a, 0x7b, 0xd3, 0xcf, 0x10, 0x45, 0x33, 0xf2, 0x0c, 0x7c, 0x1d, 0x2f, 0x66, 0xe7, 0x78,
	0x3e, 0x39, 0xdc, 0xd2, 0x90, 0xdb, 0xd8, 0x4e, 0xbe, 0x95, 0x8d, 0x0d, 0x1d, 0xc9, 0xec, 0x3e,
	0xe7, 0xdb, 0x42, 0x60, 0x74, 0x1e, 0x55, 0x82, 0xd1, 0xb2, 0xbe, 0x48, 0x8b, 0x64, 0xaf, 0x65,
	0x49, 0xd5, 0xfe, 0xab, 0x32, 0x6a, 0xf2, 0x79, 0x92, 0x80, 0xaf, 0x8f, 0xb4, 0xa9, 0x71, 0xef,
	0xa3, 0xa6, 0xd7, 0x81, 0x9a, 0x17, 0x70, 0xf2, 0x92, 0x89, 0xfa, 0x16, 0x58, 0x22, 0x5d, 0x49,
	0xfa, 0xc3, 0xdd, 0x77, 0xd1, 0x99, 0xae, 0xe7, 0xba, 0x74, 0x15, 0x5f, 0xef, 0xb6, 0xb6, 0x07,
	0x8e, 0x67, 0x66, 0xa8, 0x6a, 0xd7, 0xe4, 0xf7, 0x76, 0x50, 0xc0, 0x87, 0xec, 0xae, 0x21, 0xc3,
	0xc0, 0xda, 0xb5, 0xdf, 0x0e, 0xf3, 0xe9, 0xeb, 0xed, 0x3d, 0x7d, 0x77, 0xf5, 0x9f, 0x53, 0xf0,
	0x62, 0x64, 0x7c, 0xa0, 0x18, 0x8f, 0x35, 0xe3, 0xf7, 0xcc, 0x08, 0x1f, 0xc9, 0x81, 0x04, 0x83,
	0xad, 0x02, 0xc0, 0xfb, 0x06, 0x07, 0xed, 0x71, 0x11, 0xaf, 0xb1, 0x43, 0x36, 0x96, 0x61, 0x01,
	0x8f, 0x5a, 0x2c, 0xfe, 0x87, 0x9e, 0xf6, 0x93, 0x0b, 0xc7, 0x76, 0x30, 0xcd, 0x74, 0xe5, 0x18,
	0xd3, 0x55, 0x00, 0x43, 0x6c, 0xd5, 0x69, 0x03, 0x69, 0x2d, 0xaa, 0xe7, 0x5e, 0xea, 0x95, 0x63,
	0x25, 0x98, 0x07, 0xf6, 0x6d, 0x0a, 0xf6, 0xa6, 0x3b, 0xef, 0x70, 0xba, 0x9b, 0x48, 0xe0, 0x92,
	0x34, 0xba, 0x2c, 0x33, 0xdd, 0xc9, 0xb4, 0x2c, 0x87, 0x88, 0xb8, 0x64, 0x91, 0x60, 0x58, 0xc3,
	0x0a, 0x75, 0x43, 0x23, 0xd7, 0xb7, 0x9b, 0x44, 0xaf, 0xab, 0xc9, 0xcc, 0xd0, 0x58, 0x53, 0xe2,
	0x1b, 0xf7, 0x4e, 0x89, 0x61, 0x69, 0xb2, 0xd1, 0x39, 0xdd, 0xcd, 0x0c, 0x70, 0xff, 0x75, 0x06,
	0x7c, 0x0d, 0x70, 0xc1, 0x04, 0x65, 0x51, 0xf2, 0x5f, 0xd1, 0x1f, 0x7e, 0xd2, 0xb8, 0xec, 0x7a,
	0x87, 0xab, 0x01, 0xae, 0x7d, 0xf8, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xf3, 0xa0, 0xdd,
	0x00, 0x0c, 0x00, 0x00,
}
