etcd:
  - etcd:2279
  - etcd:2379
  - etcd:2479
  - etcd:2579

grpc:
  addr: ":8181"
  host: chat

http:
  addr: "0.0.0.0:8080"
  router: "/livechat/msg"

tcp:
  addr: "0.0.0.0:8180"
ws:
  addr: "0.0.0.0:9180"

mongo:
  host: "mongo"
  port: 27017
  db: "live-chat"
  user: ""
  pwd: ""

mysql:
  host: "mysql"
  port: 3306
  db: "live-chat"
  user: "root"
  password: "123456"
  prefix: "chat_"

redis:
  host: "redis"
  port: 6379

host: 10.0.0.218
